# Generated by Django 4.1.7 on 2023-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12),
        ),
    ]
