# Generated by Django 4.1.7 on 2023-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
