# Generated by Django 4.1.7 on 2023-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
